general/insulation.md
Overall, the insulation story is clear to me! :-) A few comments:
- What kind of value does the Energy Index (EI) exactly represent?
- Maybe emphasize that a label G house is insulated really badly (the worst you can get; therefore, a good starting point for calculating the heat demand reduction)
- Is label E the worst label for buildings?
- "The insulation costs in the table below only include the materials used." --> What are other costs? Cost of labor?
- The part about how the ECN heat demand profiles are used to create the mapping is not entirely clear to me.
- "NOTE: The insulation costs for households are dependent on the level of insulation in the present year: f.e. going from low to medium insulation is cheaper than from medium to high insulation." --> It is not entirely clear to …
=> Minor spelling fixes

general/documentation.md
Fixes https://github.com/quintel/documentation/issues/43#event-2417883558
=> Removed statement that ETM is a linear model

general/costs_imported_electricity.md
Adds documentation about uploading price curves to the ETM.
* quintel/etengine#1059
* quintel/etmodel#3070
* quintel/etsource#2071
=> Describe imported electricity price curves

docs/main/insulation.md
Fixes https://github.com/quintel/documentation/issues/58
=> Fix broken Fever link

data/api/scenario.js, docs/api/scenario-basics.md, sidebars.js
Hi! 
I had half a day 'left' today so I wrote up something on the scenario endpoint of the API. Not sure if any of you wants to check it. If you do, please take your time and feel free to make changes. If you don't, that's fine too, then we just merge it.
Happy weekend!
=> Add docs for scenario API

data/api/merit.js, docs/api/merit.md, sidebars.js
Some documentation on the Merit config endpoint. Can you do a quick check on the spelling and units @mabijkerk?
=> Add docs for Merit config API endpoint

docs/main/co2-ccus.md, docs/main/greenhouse-gases.md
This PR goes with:
- ETModel: https://github.com/quintel/etmodel/pull/4012
- ETSource: https://github.com/quintel/etsource/pull/2756
- ETDataset: https://github.com/quintel/etdataset/pull/944
- ETLocal: https://github.com/quintel/etlocal/pull/421
- documentation: https://github.com/quintel/documentation/pull/122
It contains a number of additions and improvements:
- Addition of electric inland ships for domestic navigation
- Addition of electric and hydrogen planes for domestic aviation
- Addition of hybrid flexible power-to-heat to agriculture sector
- Addition of water water heat pump without thermal storage to agriculture sector
- Possibility to delay emissions from captured CO2 for 'Other utilisation' indefinitely
- Updated inputs of Direct Air Capture
- Updated total potential of …
=> Several improvements

docs/main/co2-emission-factors.md, docs/main/co2-main-principles.md
This PR adds the following improvement:
- Adds documentation for emission factor of imported ammonia
Goes with https://github.com/quintel/etsource/pull/2801 and https://github.com/quintel/etmodel/pull/4031
=> Hydrogen improvements after testing

docs/main/scenario-tools/advanced-settings.md, docs/main/scenario-tools/using-proxies.md
Goes with https://github.com/quintel/scenario-tools/pull/26
=> Update documentation on proxies

docs/main/cost-overview-per-sector.md
See https://github.com/quintel/etmodel/issues/4065
=> Remove additional costs of EV feature

docs/main/scenario-tools/creating-and-updating.md, docs/main/scenario-tools/introduction.md, docs/main/scenario-tools/slider-comparison.md, sidebars.js, src/css/custom.css
New page 'slider comparison analysis' with 'new' label. Minor additions to 'Introduction' page.
=> Documentation of slider comparison analysis

docs/main/cost-methods.md
The modelling of costs and spatial impact of transit flows has been improved, covering:
- Costs of required import facilities of energy carriers, added to the cost export and to the detailed annual cost chart
- Spatial requirements of required import facilities of energy carriers, presented in a new table of future spatial requirements
Goes with:
- https://github.com/quintel/etsource/pull/3029
- https://github.com/quintel/documentation/pull/179
- https://github.com/quintel/etmodel/pull/4236
- https://github.com/quintel/etengine/pull/1416
- https://github.com/quintel/etdataset/pull/996
=> Transit flows cost and spatial aspects

docs/contrib/authoring-gqueries.md, docs/contrib/gql.md, sidebars.js
This PR changes the layout of the GQL documentation.
=>  Changing layout of documentation with GQL

docs/main/scenario-tools/advanced-settings.md, docs/main/scenario-tools/introduction.md, docs/main/scenario-tools/slider-comparison.md
The changes involved are:
- Addition of decimal_seperator as an advanced setting that can be changed
- Minor text changes that refer to the advanced settings pages
=> Minor updates of changing default settings for scenario-tools

docs/main/co2-ccus.md, docs/main/electricity-conversion.md, docs/main/hydrogen.md, yarn.lock
This PR adds the new kerosene modeling to the documentation
=> Hydrogen improvements kerosene

data/api/gqueries.js, docs/api/gqueries.md, sidebars.js
This PR adds documentation for the new API query endpoint
=>  Adding documentation for new API query endpoint

docs/contrib/authoring-tests.md, sidebars.js
This PR adds the general vision for testing, along with a more detailed plan for improvements for the mechanical turk tests.
=> Test documentation

docs/main/scenario-tools/creating-and-updating.md, docs/main/scenario-tools/creating-templates.md, src/css/custom.css
Updated documentation with the new features from PR https://github.com/quintel/scenario-tools/pull/40. 
- Documentation of the new features
- Subdivision in sections for obtaining and adopting scenario settings
=> Updated scenario template page

docs/main/hybrid-offshore-wind.md
Added information on modelling of availability of hybrid offshore wind components.
Goes with https://github.com/quintel/etmodel/pull/4294
=> Hybrid offshore wind availability information

docs/api/changelog.md
Is this what you meant by API changelog?
=> Update API changelog

docs/api/changelog.md, docs/api/saved-scenarios.md, docs/api/scenarios.md
Updating saved scenario and scenario docs to reflect the changes to the response.
Note - I will make another issue about this, but when I tested the create saved scenario endpoint I only got 404 "not found" errors.
=> Users in SavedScenario response API docs

docs/main/weather-conditions.md
This PR updates the links that refer to the weather conditions page in the ETM. 
Goes with:
- https://github.com/quintel/etmodel/pull/4432
- https://github.com/quintel/etlocal/pull/580
- https://github.com/quintel/documentation/pull/222
Closes https://github.com/quintel/etmodel/issues/4357
=> Update links to weather conditions page

docs/api/saved-scenarios.md, docs/main/demand.md
This PR solves https://github.com/quintel/etmodel/issues/4484. For more information, see the issue.
Goes with:
- https://github.com/quintel/mechanical_turk/pull/198
- https://github.com/quintel/etmodel/pull/4485
- https://github.com/quintel/etsource/pull/3261
=> Retire household behaviour sliders

src/css/custom.css
This PR removes the "new" and "updated" tag from all sections.
=> Update tags new and updated
